### ISSUE TITLE
fn_init.sqf breaks custom zeus scripts

### ISSUE THREAD

**Issue by assaultboy** [LISTINGS09/ZEI#11]
Due to fn_init and fn_zeus_addModules not handling the return of CuratorObjectRegistered event handler any subsequent attempts to script custom Zeus functionality is unreliable. This implementation seems to be due to the incorrect definition of the modules in cfgPatches as indicated by the comment in fn_init

In cfgPatches, the units[] definitions need to be in quotes
```c
units[] = {
	"ZEI_ListBuildings",
	"ZEI_GarrisonBuilding",
	"ZEI_InteriorFill",
	"ZEI_ObjectSwitch",
	"ZEI_ObjectFill",
	"ZEI_FindBPos",
	"ZEI_GetBuildingScheme"
};
```
As opposed to the current definitions:
```c
units[] = {
	ZEI_ListBuildings,
	ZEI_GarrisonBuilding,
	ZEI_InteriorFill,
	ZEI_ObjectSwitch,
	ZEI_ObjectFill,
	ZEI_FindBPos,
	ZEI_GetBuildingScheme
};
```

Fixing this would mean both fn_init and fn_zeus_addModules are not needed and can be removed completely.

**Comment by Bluscream** [comment]
Can you make a patch for that, please?

Also @shukari could maybe make it aswell?

**Comment by shukari** [comment]
Look while in game at the units definition... They should be strings... Arma make them... But you are right it's not the perfect way.

Edit: I will fix it when I find time this we

**Comment by Bluscream** [comment]
@shukari the problem that i have is ZEI disappearing every time after first time i open zeus. So:

1st time opening zeus (ZEI is there and i can fill buildings)
closed zeus and reopened (ZEI is missing from Modules)
all times after that (ZEI missing)

i have to restart the mission to get ZEI back

Maybe it's not related to the problem above? But i hoped so

**Comment by shukari** [comment]
My community uses https://github.com/ArmaAchilles/Achilles for better Zeus handling and we have no problems.
What for mods du you use... Can you send your rpt log?

**Comment by Bluscream** [comment]
I tried all the different things:
- zeus enhanced
- ares
- achilles

But currently i am using achilles + enhanced zeus

Which one do you want?
![image](https://user-images.githubusercontent.com/3318223/67603000-5918cb00-f767-11e9-9ebd-3dc552fc33cd.png)

**Comment by shukari** [comment]
The last or all in a zip ^^

**Comment by shukari** [comment]
I'm currently only on my mobile... Can you try only Arma3 Vanilla + Achilles + ZEI
BTW Ares is untouched for 4 years, don't try it ^^

**Comment by Bluscream** [comment]
[Arma 3.zip](https://github.com/LISTINGS09/ZEI/files/3773746/Arma.3.zip)

![image](https://user-images.githubusercontent.com/3318223/67603440-64b8c180-f768-11e9-9523-7f8e7f7a5d42.png)


>  BTW Ares is untouched for 4 years, don't try it ^^

i tried it anyway, cause why not :woman_shrugging:  :3

BTW: this gave me a idea for a [sharex feature request](https://github.com/ShareX/ShareX/issues/4454) :D

**Comment by LISTINGS09** [comment]
v1.11 tries this suggested method and it didn't seem to be working for me in Zeus - The modules still don't load. I'll probably revert it back if I don't make progress.
