### ISSUE TITLE
Request: Utilise buildingChanged event handler to stop floating objects on destroyed buildings

### ISSUE THREAD

**Issue by Seb105** [LISTINGS09/ZEI#12]
When buildings with interiors are destroyed, they leave behind floating objects. https://community.bistudio.com/wiki/Arma_3:_Event_Handlers/addMissionEventHandler#BuildingChanged could be used with the isRuin param to remove any objects associated with the garrison when it is destroyed.

**Comment by LISTINGS09** [comment]
I did look at this a long while back, the EH would fire but there was some issue after where it would refuse to end up removing all the objects.

Perhaps my approach was wrong. I will have another look at it, as it is annoying having to make any potential building indestructible just to look good.
